env:
  global:
    - ANDROID_PACKAGE="app-debug.apk"
    - ANDROID_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/demo/outputs
    - ANDROID_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$ANDROID_PACKAGE?overwrite=true"
    - IOS_PACKAGE="multiselect.zip"
    - IOS_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/demo/outputs
    - IOS_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$IOS_PACKAGE?overwrite=true"

git:
  depth: 1

branches:
  only: 
    - master

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ../demo-ng && npm run ci.tslint
    - stage: "WebPack, Build"
      os: osx
      env:
        - WebPack="12.0"
        - Type="VanillaJS"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify --copy-to "./outputs/demo.app"
    #     - cd $IOS_PACKAGE_FOLDER && zip -r $IOS_PACKAGE demo.app
    #     - "curl -v -u $SAUCE_USER:$SAUCE_KEY -X POST $IOS_SAUCE_STORAGE -H 'Content-Type: application/octet-stream' --data-binary @$IOS_PACKAGE"
    - os: osx
      env:
        - WebPack="12.0"
        - Type="Angular"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd publish 
        - sh pack.sh
        - cp package/*.tgz ../demo-ng/package.tgz
        - cd ../demo-ng
        - sed -i -e 's/\"..\/src\"/"package.tgz"/g' package.json
        - npm i
        - tns build ios --bundle --env.uglify --env.aot
    - language: android
      os: linux
      env:
        - WebPack="Android 28"
        - Type="VanillaJS"
      jdk: oraclejdk8
      before_install: nvm install 8
      script: 
        - cd demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot --copy-to "./outputs/app-debug.apk"
    #     - "curl -v -u $SAUCE_USER:$SAUCE_KEY -X POST $ANDROID_SAUCE_STORAGE -H 'Content-Type: application/octet-stream' --data-binary @$ANDROID_PACKAGE_FOLDER/$ANDROID_PACKAGE"
    - language: android
      os: linux
      env:
        - WebPack="Android 28"
        - Type="Angular"
      jdk: oraclejdk8
      before_install: nvm install 8
      script: 
        - cd publish 
        - sh pack.sh
        - cp package/*.tgz ../demo-ng/package.tgz
        - cd ../demo-ng
        - sed -i -e 's/\"..\/src\"/"package.tgz"/g' package.json
        - npm i
        - tns build android --bundle --env.uglify --env.aot
    - language: android
      env: 
        - BuildAndroid="28"
        - Type="VanillaJS"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd demo && npm run ci.android.build
    - language: android
      env: 
        - BuildAndroid="28"
        - Type="Angular"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd demo-ng && npm run ci.android.build
    - os: osx
      env: 
        - BuildiOS="12"
        - Xcode="10.0"
        - Type="VanillaJS"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd demo && npm run ci.ios.build
    - os: osx
      env: 
        - BuildiOS="12"
        - Xcode="10.0"
        - Type="Angular"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd demo-ng && npm run ci.ios.build
    # - os: linux
    #   language: android
    #   dist: precise
    #   sudo: required
    #   jdk: oraclejdk8
    #   before_script:
    #     - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
    #     - emulator -avd test -no-audio -no-window &
    #     - android-wait-for-emulator
    #   before_install:
    #     - nvm install 8
    #   script: cd src && npm run test.android
    # - os: osx
    #   language: node_js
    #   node_js: "8"
    #   jdk: oraclejdk8
    #   osx_image: xcode10.0
    #   script: cd src && npm run test.ios
    # - stage: "UI Tests"
    #   env: 
    #     - Android="28"
    #   language: node_js
    #   os: linux
    #   node_js: "10"
    #   script:
    #     - npm i -g appium
    #     - cd demo && npm i
    #     - npm run e2e -- --runType sauce.android --sauceLab --appPath app-debug.apk
    # - os: linux
    #   env: 
    #     - iOS="12"
    #   language: node_js 
    #   node_js: "8"
    #   script:
    #     - npm i -g appium
    #     - cd demo && npm i
    #     - npm run e2e -- --runType sauce.sim.iPhone7 --sauceLab --appPath multiselect.zip


android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-23
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        
before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable


